version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: dc_mysql
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
      - ./mysql/sql/:/docker-entrypoint-initdb.d
    networks:
      - default
  app:
    image: node:12.8.0
    container_name: dc_web
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./sever:/app
    working_dir: /app
    # npmでyarnをインストールしたとにseverを起動
    command: >
      bash -c "npm install -g yarn && yarn start"
    networks:
      - default
    depends_on:
      - mysql
  # phpMyAdmin
  phpmyadmin:
    container_name: dc_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
networks:
  default:
# コンテナが削除されてもデータが消えずに保持される
volumes:
  mysqldata:
